//
//  LoginCleanSwiftInteractor.swift
//  Bate Ponto
//
//  Created by Lucas Franco Bernardes on 13/02/19.
//  Copyright (c) 2019 Lucas Franco Bernardes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginCleanSwiftBusinessLogic
{
  func doSomething(request: LoginCleanSwift.Something.Request)
}

protocol LoginCleanSwiftDataStore
{
  //var name: String { get set }
}

class LoginCleanSwiftInteractor: LoginCleanSwiftBusinessLogic, LoginCleanSwiftDataStore
{
  var presenter: LoginCleanSwiftPresentationLogic?
  var worker: LoginCleanSwiftWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LoginCleanSwift.Something.Request)
  {
    worker = LoginCleanSwiftWorker()
    worker?.doSomeWork()
    
    let response = LoginCleanSwift.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
