//
//  LoginCleanSwiftViewController.swift
//  Bate Ponto
//
//  Created by Lucas Franco Bernardes on 13/02/19.
//  Copyright (c) 2019 Lucas Franco Bernardes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AKMaskField

protocol LoginCleanSwiftDisplayLogic: class
{
  func displaySomething(viewModel: LoginCleanSwift.Fetch.ViewModel)
}

class LoginCleanSwiftViewController: UIViewController, LoginCleanSwiftDisplayLogic
{
  var interactor: LoginCleanSwiftBusinessLogic?
  var router: (NSObjectProtocol & LoginCleanSwiftRoutingLogic & LoginCleanSwiftDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginCleanSwiftInteractor()
    let presenter = LoginCleanSwiftPresenter()
    let router = LoginCleanSwiftRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    //login()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var cleanButton: UIButton!
    @IBOutlet weak var passwordClean: UITextField!
    @IBOutlet weak var cpfClean: AKMaskField!
    
    @IBAction func pressedButton(_ sender: Any) {
        login()
    }
    func login()
  {
    let request = LoginCleanSwift.Fetch.Request()
    interactor?.login(request: request)
  }
    func displayMenu(){
        router!.routeToSomewhere(segue: nil)
    }
  func displaySomething(viewModel: LoginCleanSwift.Fetch.ViewModel)
  {
    router!.htmlString = viewModel.html
    router!.routeToSomewhere(segue: nil)
    
  }
}
