//
//  LoginCleanSwiftRouter.swift
//  Bate Ponto
//
//  Created by Lucas Franco Bernardes on 13/02/19.
//  Copyright (c) 2019 Lucas Franco Bernardes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginCleanSwiftRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginCleanSwiftDataPassing
{
  var dataStore: LoginCleanSwiftDataStore? { get }
  var htmlString: String? { get set }
}

class LoginCleanSwiftRouter: NSObject, LoginCleanSwiftRoutingLogic, LoginCleanSwiftDataPassing
{
    
    
  weak var viewController: LoginCleanSwiftViewController?
  var dataStore: LoginCleanSwiftDataStore?
  var htmlString: String?
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
 {
    //let viewController: LoginCleanSwiftViewController?
    
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    var destinationVC = storyboard.instantiateViewController(withIdentifier: "MenuViewController") as! MenuViewController
    passDataToSomewhere(source: dataStore!, destination: &destinationVC)
    self.navigateToSomewhere(source: viewController!, destination: destinationVC)
    
    //navigateToDetails(source: viewController!, destination: destinationVC)
    
    
    //let destinationVC = viewController?.presentingViewController as! MenuViewController
    //_ = destinationVC.htmlString
    //self.navigateToSomewhere(source: viewController!, destination: destinationVC)
    //passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  
  }
    
  // MARK: Navigation
  
  func navigateToSomewhere(source: LoginCleanSwiftViewController, destination: MenuViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: LoginCleanSwiftDataStore, destination: inout MenuViewController)
  {
    destination.htmlString = self.htmlString!
  }
}
